# 工作流名称
name: Deploy
# 触发工作流的事件
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
# 工作流里的任务
jobs:
  # 任务名，构建并部署到GitHubPages
  deploy:
    # 运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # 任务里的运行步骤
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      # 步骤名
      - name: Build
        run: npm run build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1